services:
  - type: web
    name: mi-mercado
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://techtrove_user:techtrove_password@localhost:5432/techtrove_db
    staticPublishPath: ./static
    healthCheckPath: /
    autoDeploy: true
